apiVersion: v1
kind: ConfigMap
metadata:
  name: angie-config
  namespace: homework
data:
  default.conf: |
    server {
      listen 8000;
      server_name localhost;

    root /homework;
      index index.html;

      location / {
        try_files $uri $uri/ =404;
      }
    }
