apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: homework
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: angie
    image: docker.angie.software/angie:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: homework
      mountPath: "/homework"
    - name: angie-conf
      mountPath: "/etc/angie/http.d/default.conf"
      subPath: default.conf
      readOnly: true
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  initContainers:
  - name: init-angie
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: homework
      mountPath: "/init"
  volumes:
  - name: homework
    emptyDir: {}
  - name:  angie-conf
    configMap:
      name: angie-config
