user  angie;
worker_processes  auto;
worker_rlimit_nofile 65536;

error_log  /var/log/angie/error.log notice;
pid        /run/angie/angie.pid;

events {
    worker_connections  65536;
}


http {
    include       /etc/angie/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    log_format extended '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" rt="$request_time" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'h="$host" sn="$server_name" ru="$request_uri" u="$uri" '
                        'ucs="$upstream_cache_status" ua="$upstream_addr" us="$upstream_status" '
                        'uct="$upstream_connect_time" urt="$upstream_response_time"';
#Повышение уровня лога с main на info
    error_log  /var/log/angie/error.log  info;
      #senfile Позволяет без затрат процессора, с минимальным копированием через RAM отдавать файлы

#Оптимизация SSL моединений - кэширование. 
# В 1 мегабайт кэша помещается около 4000 сессий.
    ssl_session_cache   shared:SSL:4m;
    ssl_session_timeout 5m;


    tcp_nopush on;
    # данные отправляются немедленно после получения от приложения, 
      #что снижает задержку (латентность), но увеличивает общее количество пакетов в сети. 
    tcp_nodelay on;

    keepalive_timeout 120;
    keepalive_requests 1000; 

    open_file_cache max=10000 inactive=60s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2; 

#gzip  on;
#Настройка получения сертификата HTTP
    resolver 127.0.0.11 ipv6=off;

    include /etc/angie/http.d/*.conf;
    include prometheus_all.conf;
}

#stream {
#    include /etc/angie/stream.d/*.conf;
#}
