upstream backend {
  zone upstream-backend 10m;
# hash $host consistent;
#  random; 
#two;
   server debug-white:8080;
   server debug-blue:8080;
   server debug-green:8080 backup;
   server debug-gold:8080;
}

acme_client rsa https://acme-v02.api.letsencrypt.org/directory key_type=rsa;
acme_client ecdsa https://acme-v02.api.letsencrypt.org/directory;
#____________________________________________________________
#Настройка HT consistent;TP для обновления сертификатов,
   # а также для перенаправления на HTTPS
server {
      
      listen 80 default_server reuseport;
      server_name mystend.strangled.net;

      location /.well-known/acme-challenge/ {
          root /var/www/acme;
      }

      location / {
         return 301 https://$host$request_uri;
      }

}
#__________________________________________________________
# Настройка HTTPS
server {
      listen 443 ssl reuseport;
      listen 443 quic reuseport;

      server_name  mystend.strangled.net;
#Подключение HTTP/2, HTTP/3
      http2 on;
      http3 on;

#Настройка получения сертификатов
   
      acme	rsa;
      acme	ecdsa;

      ssl_certificate	        $acme_cert_rsa;
      ssl_certificate_key 	$acme_cert_key_rsa;
      ssl_certificate		$acme_cert_ecdsa;
      ssl_certificate_key	$acme_cert_key_ecdsa;
      
#По умолчанию:
      ssl_protocols       TLSv1.2 TLSv1.3;
      ssl_ciphers         HIGH:!aNULL:!MD5;      
      ssl_session_tickets on;
#Оптимизация HTTP/2
      http2_max_concurrent_streams 128;
      http2_chunk_size 8k;
#Настройка HTTP/3
      add_header Alt-Svc 'h3=":443"; ma=86400';
      http3_max_concurrent_streams 128;
#HSTS Использование HTTPS на год
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
       
      status_zone balance;   
        
      root   /var/www/html;
      index  index.php index.htm index.html;
    
    
    error_page   500 502 503 504 404 /error/index.html;
    
    location / {
       proxy_pass http://backend;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
       proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
       proxy_next_upstream_tries 1;
       proxy_next_upstream_timeout 1s;
    
    }
    location = /error/index.html {
        internal;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #

    # deny access to .htaccess files, if Apache's document root
    # concurs with angie's one
    #
    location ~ /\.ht {
        deny  all;
    }
    
    location /console/ {
       allow 127.0.0.1;
       allow 172.16.0.0/12;
       allow 178.178.215.186;
       allow 10.0.0.0/8;
       deny all;

       auto_redirect on;
      alias /usr/share/angie-console-light/html/;
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";    
     }


    location /console/api/ {
        api /status/;
    }   


    location =/p8s {
      prometheus all;
    } 
}

