apiVersion: apps/v1
kind: Deployment
metadata:
  name:  example-deployment-1
  namespace: default
  labels:
    app:  otus
spec:
  selector:
    matchLabels:
      app: otus
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  otus
    spec:
      containers:
      - name:  app
        image: debian:12.2-slim
        # this container will be exec before start of main container
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c","echo 'hello from start pod!'> /hello_from_start.txt"]
        command:
            - /bin/bash
            - -c
            - 'echo "I am pod from Deployment"; while true; do true; done'
        # readinessProbe:
        #   exec:
        #     command:
        #       - /bin/false
