server {
      listen       80 default_server;    
      server_name  myword.ru www.myword.ru;

#localhost;
        
    #access_log  /var/log/angie/host.access.log  main;
   
        root   /var/www/html;
        index  index.php index.htm index.html;
    

    
    location / {
      try_files $uri $uri/ /index.php$is_args$args;
      add_header X-Served-By "WORDPRESS has processed DINAMIC request!!!!" always;     
    }

    
    #Location - регулярные выражения. Обработка картинок. Поиск по регуляркt.Кэширование на 30 дней
    location ~* \.(?:jpeg|jpg|png|gif|svg)$ {
         expires max;
         log_not_found off;
         add_header X-Served-By "Angie has processed STATIC request!!!!" always;        
   }


    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504 404;
    
    location = /error/index.html {
        internal;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        add_header X-Served-By "WORDPRESS has processed DINAMIC request!!!!" always;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with angie's one
    #
    location ~ /\.ht {
        deny  all;
    }
    location ~* \.(env|git|htaccess|sql|bak|backup|log)$ {
        deny all;
        return 403;
    } 
}

